version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/app/db
  
  
  api_app:
    image: api_app
    container_name: api_app
    depends_on:
      - mongodb
    build: 
      ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8000:8000"
      # - $SERVER_PORT:$SERVER_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/app/api

  react_app:
    image: react_app
    container_name: react_app
    depends_on:
      - mongodb
      - api_app
    build:
      ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./frontend:/app/frontend
    
volumes:
  db:

networks:
  stack:
    driver: bridge